apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: wordpress-example-patched
spec:
  forProvider:
    chart:
      name: wordpress
      repository: https://charts.bitnami.com/bitnami
      version: 15.2.5
    namespace: wordpress
    patchesFrom:
      - configMapKeyRef:
          key: patch.yaml
          name: wp-patch
          namespace: wordpress
          optional: false
    set:
      - name: param1
        value: value2
    values:
      param1: value1
      param2: 1
  providerRef:
    name: helm-provider
